nginx:
  image: nginx
  volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - /www/web:/usr/share/nginx/html
  ports:
    - "8080:80"
  links:
    - php:php

php:
  image: php:7.2-fpm
  expose:
    - "9000"
  links:
    - postgres
    - redis
  volumes:
    - /www/web:/usr/share/nginx/html

redis:
  image: redis
  ports:
    - "6379:6379"
  volumes:
    - /data/redis:/data
  command: redis-server --appendonly yes

postgres:
  image: postgres:11
  ports:
    - "5432:5432"
  volumes:
    - ./persistence/postgres:/var/lib/postgresql/data
    - ./createDB/init.sql:/docker-entrypoint-initdb.d/init.sql
  environment:
    - PG_PASSWORD=${POSTGRES_ROOT_PASSWORD}
